spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_files
    username: postgres
    password: lumia505
    driver-class-name: org.postgresql.Driver
  jpa:
    #generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true.
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#hibernate.ddl-auto=create-drop
server:
  port: 8085